#pragma once
#include <string>
#include <vector>
#include "Enemy.h"
#include "Area.h"
#include "time.h"

class Zone
{
	/*
	Each Zone contains Areas, the enemy is generated by the Area when it is created
	A vector of Areas, mAreas, holds all of the areas in the zone.
	*/
public:
	Zone();
	Zone(std::string zoneName);
	~Zone();

	const std::string getZoneName() { return mName; }
	std::string getEntryDialogue() { return mEntryDialogue; }
	std::string getExitDialogue() { return mExitDialogue; }

	int mNumAreas;


//private:
	std::string mName;
	std::vector<Area> mAreas;
	std::string mEntryDialogue;
	std::string mExitDialogue;

	void generateAreas();
};

